### ISSUE TITLE
Falta de identificación entre Médico y Paciente

### ISSUE THREAD

**Issue by Rossana17** [mediquo/mediquo-ios-sdk#12]
Estimados,

Al ingresar al chat con los médicos de crónicos, no se identifica la persona que escribe, es decir sale todo mezclado sin identificar el mensaje del medico y paciente, adjunto capturas:

1.- al iniciar el chat, refleja de la sgte manera:

![image](https://github.com/user-attachments/assets/e3304337-c494-48b9-b210-9e28918f81e4)

2.- luego no se identifica quien escribe

![image](https://github.com/user-attachments/assets/63c9b098-0902-4a0d-a75d-00293f237213)

La versión utilizada es: 3.0.274

![WhatsApp Image 2024-10-31 at 10 17 36 AM](https://github.com/user-attachments/assets/ec17b1a2-9c49-4cdc-9303-f1db031f06c7)
![WhatsApp Image 2024-10-31 at 10 14 30 AM](https://github.com/user-attachments/assets/48a4c7b6-9a8f-41f0-bbfe-e606541803d7)
![WhatsApp Image 2024-10-31 at 10 14 53 AM](https://github.com/user-attachments/assets/e4413d22-60f8-4036-82cf-9d017715097d)

**Comment by piercifani** [comment]
Luego de revisar vuestro binario, he visto que están usando la versión 10.2.1 de nuestro SDK 

<img width="928" alt="image" src="https://github.com/user-attachments/assets/728dc17a-73ed-49f1-8739-9631a2908ceb">

Este errores _ya fue reportado_ por ustedes (https://github.com/mediquo/mediquo-ios-sdk/issues/9) y fue corregido en las versiones siguientes. 

Rogamos actualizar el SDK a la última versión, o como mínimo a una más reciente, para evitar este problema
