### ISSUE TITLE
Espacios muertos sobre y debajo de campo de ingreso en chat  bloquean visualización de chat

### ISSUE THREAD

**Issue by fdubayteq** [mediquo/mediquo-ios-sdk#7]
**Describe the bug**
En ciertas ocaciones al estar en un chat donde hay mucho espacio muerto arriba y bajo del campo de ingreso por lo que el historial de chat queda con poco espacio de visualización

**To Reproduce**
1. Entrar a un chat
2. Hacer scroll hacia arriba y abajo para que se oculte el teclado 
3. Con el campo de ingreso en la parte inferior y sin que se muestre el teclado, adjuntar una imagen de la galería
4. Hacer scroll hacia arriba y abajo
5. Enviar un mensaje 
6. Con el campo de ingreso mostrando el teclado, adjuntar otra imagen de la galería
7.  Se visualiza espacio muerto arriba y bajo del campo de ingreso 

**Expected behavior**
- No se creen espacios muertos que bloquean la visualización del chat 

**Screenshots**
Video replicando el problema.

https://github.com/mediquo/mediquo-ios-sdk/assets/174832994/a9958862-6cd3-4236-87b6-d5029477b270

**Environment (please complete the following information):**
 - iOS Version: iOS 16.1
 - Xcode Version: 5.1 (15C65)
 - Integration: SPM

**Additional context**
Anything else you can tell us about the problem here.

**Comment by piercifani** [comment]
Hola!

Sabes si pasa esto con otras versiones de iOS 16? hemos probado en el único iPhone que nos queda en esta versión del Sistema, específicamente con iOS 16.7, y la verdad es que, a pesar de que la UX no es todo lo bonita que queremos, no logramos reproducir este problema

https://github.com/mediquo/mediquo-ios-sdk/assets/869981/3706f0d1-c5ae-450b-b748-868dd8f00b55

**Comment by piercifani** [comment]
Hola!

El único iPhone que tenemos con iOS 16 es un iPhone X que está en la última versión soportada: iOS 16.7.8

Aquí no podemos reproducir este problema con un uso normal.

https://github.com/mediquo/mediquo-ios-sdk/assets/869981/911a782c-48f4-4b7b-98b5-561d86029870

Dicho esto, en la versión 10.2.2 cambiaremos la manera en que se comporta el ScrollView con el Teclado del sistema, quizás así este problema se mitigue.

**Comment by piercifani** [comment]
Problema resuelto en la versión [10.2.2](https://github.com/mediquo/mediquo-ios-sdk/releases/tag/10.2.2)

**Comment by fdubayteq** [comment]
El problema persiste en la versión 10.2.2 

<img src="https://github.com/mediquo/mediquo-ios-sdk/assets/174832994/c48022a7-f8f8-408a-a4c5-8d36a58a0d62" width="300">

**Comment by piercifani** [comment]
Puedes reproducirlo en otras versiones más recientes de iOS?

**Comment by fdubayteq** [comment]
En un IPhone XR con iOS 17.5.1 no se ha replicado, con un iPhone XR con iOS 16.1 continúa el error incluso ahora el espacio muerto se ha incrementado. El app donde se integra el SDK tiene como versión mínima iOS 15 por lo que debe funcionar correctamente en estas versiones.

**Comment by piercifani** [comment]
> El app donde se integra el SDK tiene como versión mínima iOS 15 por lo que debe funcionar correctamente en estas versiones.

Si, lo se, solo intento aislar el problema.

Tenéis algún tipo de configuración usando [UIAppereance](https://developer.apple.com/documentation/uikit/uiappearance) para customizar vuestra app?

Puedes reproducir este error con alguna de las apps de ejemplo?

**Comment by fdubayteq** [comment]
Con el demo también se replica el error. Como nota el mensaje de "Not available" debería esta en español. 

<img src="https://github.com/mediquo/mediquo-ios-sdk/assets/174832994/abdbbe83-0885-447d-9595-3b6ff7e7a659" width="300">

**Comment by piercifani** [comment]
Gracias.

Estudiamos alternativas para sistemas operativos legacy y te decimos algo asap

**Comment by piercifani** [comment]
Puedes probar con la versión https://github.com/mediquo/mediquo-ios-sdk/releases/tag/10.2.3? Ya no lo logro reproducir yo en esta.

Gracias!

**Comment by fdubayteq** [comment]
Con la versión 10.2.3 pasa menos pero cuando se da tap en el botón "+" se incrementan las espacios muertos

<img src="https://github.com/mediquo/mediquo-ios-sdk/assets/174832994/1ff9e6f5-be56-4283-9a2e-ca49e3b183f4" width="300">

**Comment by piercifani** [comment]
Puedes compartir un record screen?

**Comment by fdubayteq** [comment]
Adjunto el video 


https://github.com/mediquo/mediquo-ios-sdk/assets/174832994/2b4e3f0a-280a-4b38-b6ab-9ab140e78c84

**Comment by piercifani** [comment]
Muchas gracias @fdubayteq!

Viendo el Screen Record que envías, vemos que la funcionalidad no se encuentra afectada ya que la UI recupera eventualmente el estado correcto.

Así que podríamos catalogar este error como **cosmético**.

Esto, sumado a que sólo ocurre en dispositivos cuya versión de iOS es anterior a la de 16.7, nos lleva a concluir que este error no debe bloquear la integración del SDK.

Vamos a proceder a crear un [nuevo issue](https://github.com/mediquo/mediquo-ios-sdk/issues/10) con toda la información que gentilmente nos has enviado y ponerlo en nuestro backlog para resolverlo en futuras iteraciones.

Muchas gracias!
