### ISSUE TITLE
Server Error al registrar token push 

### ISSUE THREAD

**Issue by fdubayteq** [mediquo/mediquo-ios-sdk#8]
**Describe the bug**
Server Error al registrar token push con el método setPushNotificationToken 

**To Reproduce**
1. Obtener token de data del método didRegisterForRemoteNotificationsWithDeviceToken type: .appleAPNS
2. Instanciar clase MediQuo con api key y userID
3. Ejecutar método setPushNotificationToken con token recibido
4. En la consola se tiene el error: 
_[APIClient.Response] StatusCode: 500 Path: /notifications/v1/push-token
[APIClient.Response] Error Message: {
    "message": "Server Error"
}_

**Expected behavior**
Recibir éxito al registrar push y poder recibir notificaciones push. 

**Screenshots**

**Environment (please complete the following information):**
 - iOS Version: iOS 16.1
 - Xcode Version:  15.1 (15C65)
 - Integration: SPM

**Additional context**
Anything else you can tell us about the problem here.

**Comment by piercifani** [comment]
Hola!

He revisado los detalles de su integración, y resulta que ustedes tienen la integración de pushes configurada con Firebase y no con Apple APNS.

Es por ello que deben primero obtener el [token de Firebase](https://firebase.google.com/docs/cloud-messaging/ios/client#fetching-the-current-registration-token) y una vez obtenido, debes dárselo al SDK de Mediquo utilizando la siguiente llamada: 

`try await mediquo.setPushNotificationToken(data, type: .firebase)`

Una vez hagas esto, el error 500 debería desaparecer.

**Comment by piercifani** [comment]
Para evitar estos errores en el futuro, hemos procedido a actualizar el README del repositorio

https://github.com/mediquo/mediquo-ios-sdk/commit/ab0df9fee5b15de74fad9eb3b62b910c6a61003e

**Comment by fdubayteq** [comment]
Se ha probado realizar el registro con firebase convirtiendo el Messaging.messaging().fcmToken a Data con encoding utf8 y se ha obtenido el mismo error:

[APIClient.Response] StatusCode: 500 Path: /notifications/v1/push-token
[APIClient.Response] Error Message: {
"message": "Server Error"
}

**Comment by piercifani** [comment]
Puedes volver a intentar? Hemos vuelto a subir un fix

**Comment by fdubayteq** [comment]
Ahora se logrado tener éxito para registrar el token pero no llegan las notificaciones push en el ambiente de pruebas,  tal vez en necesario actualizar algún key ?

[APIClient.Response] StatusCode: 200 Path: /notifications/v1/push-token
ready

**Comment by juancavaplatas** [comment]
Buen dia, para recibir las notificaciones push se requiere un profesional conectado en vuestra integración. 

Para ello necesitaremos un registro en la plataforma para profesionales https://web.mediquo.com/. Luego, podeis enviar al contacto de soporte de MediQuo los detalles para configurar a este profesional en vuestra integración. Cuando esté configurado, se pueden intercambiar mensajes y recibir notificaciones push del lado del paciente.

**Comment by fdubayteq** [comment]
Si, ya se tiene acceso a la plataforma de profesionales y se ha intercambiado mensajes pero las notificaciones push no han llegado.

**Comment by juancavaplatas** [comment]
Buen dia, el departamento técnico se pondrá en contacto para comprobar la configuración de Firebase aplicada (https://developer.mediquo.com/docs/sdk/android/introduction/#push-notifications-handling)
