### ISSUE TITLE
Mensajes enviados aparecen en lado izquierdo de pantalla como que hubiera sido el receptor el que escribió los mensajes

### ISSUE THREAD

**Issue by fdubayteq** [mediquo/mediquo-ios-sdk#9]
**Describe the bug**
Mensajes enviados aparecen en lado izquierdo de pantalla como que hubiera sido el receptor el que escribió los mensajes

**To Reproduce**
1. Ir a un chat
2. Enviar un mensaje, el mismo aparece la derecha de la pantalla
3. Regresar a listado de chat
4. Regresar a chat donde se envió mensaje 
5. Mensajes enviados aparecen en lado izquierdo de pantalla

**Expected behavior**
Mensajes enviados deben aparecer en lado derecha de pantalla luego de retomar un chat

**Screenshots**

**Environment (please complete the following information):**
 - iOS Version: iOS 16.1
 - Xcode Version: 15.1 (15C65)
 - Integration: SPM

**Additional context**
Anything else you can tell us about the problem here.

**Comment by piercifani** [comment]
Hola! Gracias por reportar este error.

Puedes enviar un screen record como has hecho en https://github.com/mediquo/mediquo-ios-sdk/issues/7 para poder ver que está pasando? En la app de ejemplo no logro reproducir esta situación.

https://github.com/mediquo/mediquo-ios-sdk/assets/869981/3f093a0c-94bd-4a67-9d1e-b246b6632957

**Comment by piercifani** [comment]
Después de revisar con el equipo este problema, hemos podido reproducirlo.

Informaremos por aquí de su solución, gracias!

**Comment by piercifani** [comment]
Problema resuelto en la versión [10.2.2](https://github.com/mediquo/mediquo-ios-sdk/releases/tag/10.2.2)

**Comment by fdubayteq** [comment]
En la versión 10.2.2 ya no ha dado este problema.
